version: 2.1
orbs:
  build-and-test:
    jobs:
      build-and-test:
        parameters:
          script:
            description: the script to execute
            type: string
        machine: true
        working_directory: ~/monolithic-customers-and-orders
        steps:
          - checkout
          - restore_cache:
              keys:
                - monolithic-customers-and-orders-{{ checksum "gradle.properties" }}
                - monolithic-customers-and-orders-
          - run:
              command: |
                ./.circleci/upgrade-docker-compose.sh
                . ./.circleci/setenv-circle-ci.sh
                ./gradlew testClasses
          - save_cache:
              paths:
                - ~/.gradle
              key: monolithic-customers-and-orders-{{ checksum "gradle.properties" }}
          - run:
              command: |
                . ./.circleci/setenv-circle-ci.sh
                <<parameters.script>>
          - run:
              name: Save test results
              command: |
                mkdir -p ~/junit
                find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
              when: always
          - run:
              name: Print container logs
              command: |
                export TERM=dumb
                ./.circleci/print-container-logs.sh
              when: always
          - store_test_results:
              path: ~/junit
          - store_artifacts:
              path: ~/junit
          - store_artifacts:
              path: ~/container-logs
workflows:
  version: 2.1
  build-test-and-deploy:
    jobs:
      - build-and-test/build-and-test:
          name: ./build-and-test-all
          script: ./build-and-test-all.sh

