name: Build

on:
  push:
  pull_request:
    types:
      - opened
      - edited
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      run: ./build-and-test-all.sh
